Updates to allow autoconfig based on memory
starkandwayne/habitat-plans pull request #19
Opened 2017-05-11 07:47 UTC by jamessewell

new config file created in run hook, then loaded in postgresql.conf through an include

2017-05-11 08:00 UTC, bodymindarts requested changes
Please use the `{{}}` interpolation for the directories.. the rest looks good!

2017-05-11 08:00 UTC, bodymindarts commented on postgresql/hooks/run
> +export PGDATA=/hab/svc/postgresql/data
Please don't hard code this, use the `{{}}` handlebars interpolation. The data dir in perticular may become configurable in a later hab version to support different mount points for persistent volumes.

2017-05-11 08:00 UTC, bodymindarts commented on postgresql/hooks/run
> +cat > /hab/svc/postgresql/config/postgresql.local.conf <<-LOCAL
This should be extracted into a function, but that can be done later.

2017-05-12 02:02 UTC, closed without merging

2017-05-12 02:02 UTC, jamessewell commented
Updated to new request