PG: Updates to config
starkandwayne/habitat-plans pull request #23
Opened 2017-05-12 03:49 UTC by jamessewell

- added some values in postgresql.conf
- added support for sync replication
- changed creation of REPLICATION user to be async to avoid deadlock
- added an option to use data checksums for initdb

2017-05-12 06:07 UTC, bodymindarts requested changes

2017-05-12 06:07 UTC, bodymindarts commented on postgresql/default.toml
> +synchronous = true
Don't think this should be on by default

2017-05-12 06:07 UTC, bodymindarts commented on postgresql/default.toml
> +synchronous_standby_names = '*'
Don't know if this should be editable. Ideally hab would just figure everything out by itself.

2017-05-12 06:07 UTC, bodymindarts commented on postgresql/hooks/init
> +    --locale POSIX {{ #if cfg.data_checksums }}--data-checksums{{ /if }}
From reading a bit about this setting I would say we have it on by default or? It protects against data corruption but doesn't seem to have any downside to it.

2017-05-12 06:07 UTC, bodymindarts commented on postgresql/default.toml
> +data_checksums = true
Why would anyone wan't to turn this off? Does it really need to be configurable?

2017-05-12 06:09 UTC, bodymindarts commented on postgresql/default.toml
> +data_checksums = true
Okay so it makes things a bit slower.... so it allows ppl to choose fast over correct I guess.

2017-05-15 02:05 UTC, jamessewell commented on postgresql/default.toml
> +data_checksums = true
Good point actually, I think you are right and we just leave it on till there is a use case for off?

2017-05-15 02:05 UTC, jamessewell commented on postgresql/default.toml
> +synchronous = true
Agree

2017-05-15 02:07 UTC, jamessewell commented on postgresql/default.toml
> +synchronous_standby_names = '*'
I think we have a lot of customers who would want this - but to make it useful you actually need to manage the `application_name` of the standby servers. Probably too complex for the initial release. 

I'll take it out and always use * and maybe return to it later.

2017-05-16 08:31 UTC, bodymindarts approved these changes

2017-05-16 08:32 UTC, merged